version: '3.8'

services:
  k6:
    image: grafana/k6:latest
    volumes:
      - ./:/k6
    environment:
      - BASE_URL=${BASE_URL:-http://host.docker.internal:3001}
    network_mode: "host"
    command: run /k6/smoke-test.js
